ALTER TABLE passenger
    ADD COLUMN password VARCHAR(255) NOT NULL,
    ADD COLUMN phone_number VARCHAR(255) NOT NULL,
    ADD COLUMN email VARCHAR(255) NOT NULL,
    ADD COLUMN name VARCHAR(255) NOT NULL,
    MODIFY COLUMN name VARCHAR(255) NOT NULL;
